
[server]
host = "0.0.0.0"
port = 4040

[database]
host = "localhost"
port = 5432
database = "geoengine"
schema = "geoengine"
user = "geoengine"
password = "geoengine"
# Set to `true` to start with a fresh database each time.
# If this parameter is set to `false` at the first start, subsequent changes to `true` will result in an error.
# This helps to protect production environments from unwanted data loss.
clear_database_on_start = false
