GET http://localhost:4040/

###

GET http://localhost:4040/processes

###

GET http://localhost:4040/processes/hello

###

POST http://localhost:4040/processes/hello/execution
Content-Type: application/json

{
  "inputs": {
    "name": "foo"
  },
  "outputs": {
    "sentence": {
      "format": {
        "mediaType": "text/plain",
        "encoding": "utf-8"
      },
      "transmissionMode": "value"
    }
  }
}

###

GET http://localhost:4040/test

###

POST http://localhost:4040/processes/greet/execution
Content-Type: application/json

{
  "inputs": {
    "name": "World"
  }
}
