# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/db/schema.rs"
import_types = []
custom_type_derives = ["Debug"]
with_docs = true
allow_tables_to_appear_in_same_query_config = "fk_related_tables"
filter = { except_tables = ["_sqlx_migrations", "spatial_ref_sys"] }

[migrations_directory]
dir = "migrations"
