---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: biois-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local

---
apiVersion: v1
kind: Pod
metadata:
  name: biois
spec:
  # keep restart policy to Always to mimic Deployment behavior
  restartPolicy: Always
  containers:
    - name: frontend
      image: biois-frontend:latest
      ports:
        - containerPort: 80
          hostPort: 4200
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
    - name: backend
      image: biois-backend:latest
      # ports:
      #   - containerPort: 8080
      #     hostPort: 8080
      # ports:
      #   - containerPort: 3030
      #     hostPort: 3030
      readinessProbe:
        httpGet:
          path: /health
          port: 4040
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /health
          port: 4040
        initialDelaySeconds: 15
        periodSeconds: 10
      envFrom:
        - configMapRef:
            name: biois-config
        - secretRef:
            name: biois-postgres-secret
    - name: postgres
      image: docker.io/postgres:18-alpine
      # ports:
      #   - containerPort: 5432
      #     hostPort: 5432
      envFrom:
        - secretRef:
            name: biois-postgres-secret
      readinessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 15
        periodSeconds: 10
      volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: biois-postgres-data
