use std::pin::Pin;

use anyhow::{Context, Result};
use bb8::CustomizeConnection;
use diesel_async::{
    AsyncConnection, AsyncMigrationHarness, AsyncPgConnection, SimpleAsyncConnection,
    pooled_connection::{
        AsyncDieselConnectionManager, PoolError,
        bb8::{Pool, PooledConnection as Bb8PooledConnection},
    },
};
use diesel_migrations::{EmbeddedMigrations, MigrationHarness, embed_migrations};
use tracing::info;

mod mapping;
pub mod model;
pub mod schema; // auto-generated by diesel

pub type DbPool = Pool<AsyncPgConnection>;
pub type PooledConnection<'c> = Bb8PooledConnection<'c, AsyncPgConnection>;

const MIGRATIONS: EmbeddedMigrations = embed_migrations!("migrations");

fn run_migrations(connection: PooledConnection<'static>) -> Result<()> {
    let mut harness = AsyncMigrationHarness::new(connection);

    let versions = harness
        .run_pending_migrations(MIGRATIONS)
        .map_err(anyhow::Error::from_boxed)
        .context("Failed to run database migrations")?;

    for version in versions {
        info!("Applied migration: {version}");
    }

    Ok(())
}

/// Create a database pool and run migrations
pub async fn setup_db(config: &crate::config::Database) -> Result<DbPool> {
    let manager =
        AsyncDieselConnectionManager::<AsyncPgConnection>::new(config.connection_string());

    let db_pool_builder = Pool::builder();

    let db_pool_builder = if cfg!(test) {
        db_pool_builder
            .max_size(1) // Use a single connection for tests
            .connection_customizer(Box::new(TestCustomizer))
    } else {
        db_pool_builder
            .max_size(8) // TODO: investigate a good size
            .connection_customizer(Box::new(SchemaSettingConnectionCustomizer {
                schema: config.schema.clone(),
            }))
    };

    let db_pool = db_pool_builder
        .build(manager)
        .await
        .context("Failed to create db pool.")?;

    on_startup(
        db_pool.get_owned().await?,
        &config.schema,
        config.clear_database_on_start,
    )
    .await?;

    Ok(db_pool)
}

async fn on_startup(
    mut db_connection: PooledConnection<'static>,
    schema: &str,
    clear_database_on_start: bool,
) -> Result<()> {
    if clear_database_on_start {
        // TODO: prohibit deletion in production environments,
        // e.g., not deleting when `clear_database_on_start` was previously `false`

        info!("Clearing database schema '{schema}'");

        db_connection
            .batch_execute(&format!("DROP SCHEMA IF EXISTS {schema} CASCADE;"))
            .await
            .context("Failed to clear database schema")?;
    }

    db_connection
        .batch_execute(&format!("CREATE SCHEMA IF NOT EXISTS {schema};"))
        .await
        .context("Failed to create database schema")?;

    run_migrations(db_connection)
}

/// A connection customizer that sets the `search_path` to a specific schema upon acquiring a connection.
#[derive(Debug)]
struct SchemaSettingConnectionCustomizer {
    schema: String,
}

impl CustomizeConnection<AsyncPgConnection, PoolError> for SchemaSettingConnectionCustomizer {
    fn on_acquire<'a>(
        &'a self,
        conn: &'a mut AsyncPgConnection,
    ) -> Pin<Box<dyn Future<Output = Result<(), PoolError>> + Send + 'a>> {
        let schema = self.schema.clone();
        Box::pin(async move {
            conn.batch_execute(&format!("SET search_path TO {schema};"))
                .await
                .map_err(PoolError::QueryError)
        })
    }
}

/// A connection customizer designed for use in tests. Implements
/// [`CustomizeConnection`] in a way that ensures transactions
/// in a pool customized by it are never committed.
///
/// Built after [`diesel::r2d2::TestCustomizer`]
#[derive(Debug)]
struct TestCustomizer;

impl CustomizeConnection<AsyncPgConnection, PoolError> for TestCustomizer {
    fn on_acquire<'a>(
        &'a self,
        conn: &'a mut AsyncPgConnection,
    ) -> Pin<Box<dyn Future<Output = Result<(), PoolError>> + Send + 'a>> {
        Box::pin(async move {
            conn.begin_test_transaction()
                .await
                .map_err(PoolError::QueryError)
        })
    }
}
