use anyhow::{Context, Result};
use diesel::{
    PgConnection,
    connection::SimpleConnection,
    r2d2::{ConnectionManager, CustomizeConnection, Pool},
};
use diesel_migrations::{EmbeddedMigrations, MigrationHarness, embed_migrations};
use tracing::info;

mod mapping;
pub mod model;
pub mod schema; // auto-generated by diesel

pub type DbPool = Pool<ConnectionManager<PgConnection>>;

const MIGRATIONS: EmbeddedMigrations = embed_migrations!("migrations");

fn run_migrations(connection: &mut PgConnection) -> Result<()> {
    let versions = connection
        .run_pending_migrations(MIGRATIONS)
        .map_err(anyhow::Error::from_boxed)
        .context("Failed to run database migrations")?;

    for version in versions {
        info!("Applied migration: {version}");
    }

    Ok(())
}

/// Create a database pool and run migrations
pub fn setup_db(config: &crate::config::Database) -> Result<DbPool> {
    let manager = ConnectionManager::<PgConnection>::new(config.connection_string()?);

    let db_pool_builder = Pool::builder();

    let db_pool_builder = if cfg!(test) {
        db_pool_builder
            .max_size(1) // Use a single connection for tests
            .connection_customizer(Box::new(diesel::r2d2::TestCustomizer))
    } else {
        db_pool_builder
            .max_size(8) // TODO: investigate a good size
            .connection_customizer(Box::new(SchemaSettingConnectionCustomizer {
                schema: config.schema.clone(),
            }))
    };

    let db_pool = db_pool_builder
        .build(manager)
        .context("Failed to create db pool.")?;

    let mut db_connection = db_pool.get()?;
    let schema = config.schema.as_str();

    if config.clear_database_on_start {
        // TODO: prohibit deletion in production environments,
        // e.g., not deleting when `clear_database_on_start` was previously `false`

        info!("Clearing database schema '{schema}'");

        db_connection
            .batch_execute(&format!("DROP SCHEMA IF EXISTS {schema} CASCADE;"))
            .context("Failed to clear database schema")?;
    }

    db_connection
        .batch_execute(&format!("CREATE SCHEMA IF NOT EXISTS {schema};"))
        .context("Failed to create database schema")?;

    run_migrations(&mut db_connection)?;

    Ok(db_pool)
}

/// A connection customizer that sets the `search_path` to a specific schema upon acquiring a connection.
#[derive(Debug)]
struct SchemaSettingConnectionCustomizer {
    schema: String,
}
impl CustomizeConnection<PgConnection, diesel::r2d2::Error> for SchemaSettingConnectionCustomizer {
    fn on_acquire(&self, conn: &mut PgConnection) -> Result<(), diesel::r2d2::Error> {
        let schema = self.schema.as_str();
        conn.batch_execute(&format!("SET search_path TO {schema};"))
            .map_err(diesel::r2d2::Error::QueryError)
    }
}
