// @generated automatically by Diesel CLI.

/// A module containing custom SQL type definitions
///
/// (Automatically generated by Diesel.)
pub mod sql_types {
    /// The `JobType` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(Debug, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "JobType"))]
    pub struct JobType;

    /// The `Link` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(Debug, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "Link"))]
    pub struct Link;

    /// The `Response` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(Debug, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "Response"))]
    pub struct Response;

    /// The `StatusCode` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(Debug, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "StatusCode"))]
    pub struct StatusCode;
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::JobType;
    use super::sql_types::StatusCode;
    use super::sql_types::Link;
    use super::sql_types::Response;

    /// Representation of the `jobs` table.
    ///
    /// (Automatically generated by Diesel.)
    jobs (job_id) {
        /// The `job_id` column of the `jobs` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        job_id -> Text,
        /// The `process_id` column of the `jobs` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        process_id -> Nullable<Text>,
        /// The `job_type` column of the `jobs` table.
        ///
        /// Its SQL type is `JobType`.
        ///
        /// (Automatically generated by Diesel.)
        job_type -> JobType,
        /// The `status` column of the `jobs` table.
        ///
        /// Its SQL type is `StatusCode`.
        ///
        /// (Automatically generated by Diesel.)
        status -> StatusCode,
        /// The `message` column of the `jobs` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        message -> Nullable<Text>,
        /// The `created` column of the `jobs` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created -> Timestamptz,
        /// The `finished` column of the `jobs` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        finished -> Nullable<Timestamptz>,
        /// The `updated` column of the `jobs` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated -> Timestamptz,
        /// The `progress` column of the `jobs` table.
        ///
        /// Its SQL type is `Nullable<Int2>`.
        ///
        /// (Automatically generated by Diesel.)
        progress -> Nullable<Int2>,
        /// The `links` column of the `jobs` table.
        ///
        /// Its SQL type is `Array<Nullable<Link>>`.
        ///
        /// (Automatically generated by Diesel.)
        links -> Array<Nullable<Link>>,
        /// The `response` column of the `jobs` table.
        ///
        /// Its SQL type is `Response`.
        ///
        /// (Automatically generated by Diesel.)
        response -> Response,
        /// The `results` column of the `jobs` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        results -> Nullable<Jsonb>,
        /// The `user_id` column of the `jobs` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
    }
}
