-- Quoted types are generated by toasty-cli
-- noqa: disable=RF06

-- CREATE TYPE "Response" AS ENUM ('raw', 'document');
-- CREATE TYPE "JobType" AS ENUM ('process');
-- CREATE TYPE "StatusCode" AS
-- ENUM ('accepted', 'running', 'successful', 'failed', 'dismissed');

CREATE TABLE "credits" (
    "timestamp" BIGINT NOT NULL,
    "job_id" UUID NOT NULL,
    "computation_id" UUID NOT NULL,
    "credits" BIGINT,
    PRIMARY KEY ("job_id", "computation_id")
);

CREATE INDEX "index_credits_by_job_id" ON "credits" ("job_id");

ALTER TABLE "jobs" RENAME TO "jobs_old";

CREATE TABLE "jobs" (
    "job_id" UUID NOT NULL,
    "process_id" TEXT,
    "job_type" "JobType" NOT NULL,
    "status" "StatusCode" NOT NULL,
    "message" TEXT,
    "created" BIGINT NOT NULL,
    "finished" BIGINT,
    "updated" BIGINT NOT NULL,
    "progress" SMALLINT,
    "links" JSONB NOT NULL,
    "response" "Response" NOT NULL,
    "results" JSONB,
    "user_id" UUID NOT NULL,
    PRIMARY KEY ("job_id")
);

INSERT INTO "jobs" (
    "job_id",
    "process_id",
    "job_type",
    "status",
    "message",
    "created",
    "finished",
    "updated",
    "progress",
    "links",
    "response",
    "results",
    "user_id"
)
SELECT
    "job_id"::UUID,
    "process_id",
    "job_type",
    "status",
    "message",
    -- Unix timestamp in milliseconds
    (EXTRACT(EPOCH FROM "created") * 1000)::BIGINT AS "created",
    CASE
        WHEN "finished" IS NULL THEN NULL
        -- Unix timestamp in milliseconds
        ELSE (EXTRACT(EPOCH FROM "finished") * 1000)::BIGINT
    END AS "finished",
    -- Unix timestamp in milliseconds
    (EXTRACT(EPOCH FROM "updated") * 1000)::BIGINT AS "updated",
    "progress",
    TO_JSONB("links") AS "links",
    "response",
    "results",
    "user_id"
FROM "jobs_old";

-- Drop manually after checking that the migration worked as expected.
-- This is a safety measure to prevent accidental data loss.
DO $$ 
BEGIN 
    IF EXISTS (SELECT 1 FROM "jobs_old") THEN 
        RAISE NOTICE 'Table "jobs_old" contains data. Skipping drop operation.';
    ELSE 
        DROP TABLE "jobs_old";
    END IF;
END $$;
