/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AdditionalParameter } from '../models/AdditionalParameter';
import { Metadata } from '../models/Metadata';
import { HttpFile } from '../http/http';

export class AdditionalParameters extends Metadata {
    'parameters': Array<AdditionalParameter>;

    static override readonly discriminator: string | undefined = undefined;

    static override readonly mapping: {[index: string]: string} | undefined = undefined;

    static override readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "Array<AdditionalParameter>",
            "format": ""
        }    ];

    static override getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(AdditionalParameters.attributeTypeMap);
    }

    public constructor() {
        super();
    }
}
