/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Constraints12 } from '../models/Constraints12';
import { StringFieldMissingValues } from '../models/StringFieldMissingValues';
import { HttpFile } from '../http/http';

/**
* The field contains data which can be parsed as a valid JSON array.
*/
export class ArrayField {
    /**
    * A name for this field.
    */
    'name': string;
    /**
    * A human-readable title.
    */
    'title'?: string;
    /**
    * A text description. Markdown is encouraged.
    */
    'description'?: string;
    /**
    * An example value for the field.
    */
    'example'?: string;
    'missingValues'?: StringFieldMissingValues;
    /**
    * The type keyword, which `MUST` be a value of `array`.
    */
    'type': ArrayFieldTypeEnum;
    /**
    * There are no format keyword options for `array`: only `default` is allowed.
    */
    'format'?: ArrayFieldFormatEnum;
    'constraints'?: Constraints12;
    /**
    * The RDF type for this field.
    */
    'rdfType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "example",
            "baseName": "example",
            "type": "string",
            "format": ""
        },
        {
            "name": "missingValues",
            "baseName": "missingValues",
            "type": "StringFieldMissingValues",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ArrayFieldTypeEnum",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "ArrayFieldFormatEnum",
            "format": ""
        },
        {
            "name": "constraints",
            "baseName": "constraints",
            "type": "Constraints12",
            "format": ""
        },
        {
            "name": "rdfType",
            "baseName": "rdfType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ArrayField.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ArrayFieldTypeEnum {
    Array = 'array'
}
export enum ArrayFieldFormatEnum {
    Default = 'default'
}

