/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BiodiversitySensitiveAreasProcessInputs } from '../models/BiodiversitySensitiveAreasProcessInputs';
import { Response } from '../models/Response';
import { HttpFile } from '../http/http';

/**
* Process execution (Biodiversity Sensitive Areas – ESRS E4 B5)
*/
export class BiodiversitySensitiveAreasProcessParams {
    'inputs': BiodiversitySensitiveAreasProcessInputs;
    'outputs'?: { [key: string]: any; };
    'response'?: Response;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "BiodiversitySensitiveAreasProcessInputs",
            "format": ""
        },
        {
            "name": "outputs",
            "baseName": "outputs",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "Response",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BiodiversitySensitiveAreasProcessParams.attributeTypeMap;
    }

    public constructor() {
    }
}


