/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClimateVariable } from "../models/ClimateVariable";
import { PointGeoJsonInput } from "../models/PointGeoJsonInput";

/**
 * User-supplied inputs for the climate risk process.
 */
export class ClimateRiskInputs {
  "coordinate": PointGeoJsonInput;
  /**
   * Year of reporting or change (e.g., 2023, 2024, etc.)
   */
  "yearBegin"?: number;
  /**
   * Length of a time window in years (e.g., 5 years).
   */
  "yearRange"?: number;
  /**
   * Year of reporting or change (e.g., 2023, 2024, etc.)
   */
  "referenceYearBegin": number;
  "variables"?: Array<ClimateVariable>;
  "models"?: Array<string>;

  static readonly discriminator: string | undefined = undefined;

  static readonly mapping: { [index: string]: string } | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "coordinate",
      baseName: "coordinate",
      type: "PointGeoJsonInput",
      format: "",
    },
    {
      name: "yearBegin",
      baseName: "yearBegin",
      type: "number",
      format: "int32",
    },
    {
      name: "yearRange",
      baseName: "yearRange",
      type: "number",
      format: "int32",
    },
    {
      name: "referenceYearBegin",
      baseName: "referenceYearBegin",
      type: "number",
      format: "int32",
    },
    {
      name: "variables",
      baseName: "variables",
      type: "Array<ClimateVariable>",
      format: "",
    },
    {
      name: "models",
      baseName: "models",
      type: "Array<string>",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return ClimateRiskInputs.attributeTypeMap;
  }

  public constructor() {}
}
