/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClimateRiskInputs } from '../models/ClimateRiskInputs';
import { DataResource } from '../models/DataResource';
import { HttpFile } from '../http/http';

/**
* Output of the climate risk process: summary table and raw ensemble data.
*/
export class ClimateRiskOutputs {
    'inputs'?: ClimateRiskInputs | null;
    /**
    * Analysis window as `\"2041–2070\"`, used for display in result headlines.
    */
    'analysisPeriod'?: string | null;
    /**
    * Reference window used for anomalies as `\"2006–2025\"`, `None` when no reference period.
    */
    'referencePeriod'?: string | null;
    'climateRisk'?: DataResource | null;
    'rawEnsembleData'?: DataResource | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "ClimateRiskInputs",
            "format": ""
        },
        {
            "name": "analysisPeriod",
            "baseName": "analysisPeriod",
            "type": "string",
            "format": ""
        },
        {
            "name": "referencePeriod",
            "baseName": "referencePeriod",
            "type": "string",
            "format": ""
        },
        {
            "name": "climateRisk",
            "baseName": "climateRisk",
            "type": "DataResource",
            "format": ""
        },
        {
            "name": "rawEnsembleData",
            "baseName": "rawEnsembleData",
            "type": "DataResource",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClimateRiskOutputs.attributeTypeMap;
    }

    public constructor() {
    }
}
