/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Climate variable to compute (WMO-based daily threshold indicators).
 */
export enum ClimateVariable {
  HeatDays = "heatDays",
  IceDays = "iceDays",
  TropicalNights = "tropicalNights",
  FrostDays = "frostDays",
  DryDays = "dryDays",
  HeavyRainDays = "heavyRainDays",
}
