/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClimateRiskInputs } from "../models/ClimateRiskInputs";
import { DataResource } from "../models/DataResource";

/**
 * Response body of a climate-risk execution: one summary table per computed scenario, plus the optional `inputs` echo and `rawEnsembleData`. Which scenario keys are present depends on the requested outputs and on the model registry (`conf/nexgddp_models.toml`); the process description\'s `outputs` is the authoritative list for a given deployment.
 */
export class ClimateRiskProcessResponses {
  "ssp245"?: DataResource | null;
  "ssp370"?: DataResource | null;
  "ssp585"?: DataResource | null;
  "rawEnsembleData"?: DataResource | null;
  /**
   * The submitted inputs, echoed back.
   */
  "inputs"?: ClimateRiskInputs | null;

  static readonly discriminator: string | undefined = undefined;

  static readonly mapping: { [index: string]: string } | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "ssp245",
      baseName: "ssp245",
      type: "DataResource",
      format: "",
    },
    {
      name: "ssp370",
      baseName: "ssp370",
      type: "DataResource",
      format: "",
    },
    {
      name: "ssp585",
      baseName: "ssp585",
      type: "DataResource",
      format: "",
    },
    {
      name: "rawEnsembleData",
      baseName: "rawEnsembleData",
      type: "DataResource",
      format: "",
    },
    {
      name: "inputs",
      baseName: "inputs",
      type: "ClimateRiskInputs",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return ClimateRiskProcessResponses.attributeTypeMap;
  }

  public constructor() {}
}
