/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClimateRiskInputs } from "../models/ClimateRiskInputs";
import { Response } from "../models/Response";

/**
 * Process execution (Climate Risk)
 */
export class ClimateRiskProcessParams {
  "inputs": ClimateRiskInputs;
  "outputs"?: { [key: string]: any };
  "response"?: Response;

  static readonly discriminator: string | undefined = undefined;

  static readonly mapping: { [index: string]: string } | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "inputs",
      baseName: "inputs",
      type: "ClimateRiskInputs",
      format: "",
    },
    {
      name: "outputs",
      baseName: "outputs",
      type: "{ [key: string]: any; }",
      format: "",
    },
    {
      name: "response",
      baseName: "response",
      type: "Response",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return ClimateRiskProcessParams.attributeTypeMap;
  }

  public constructor() {}
}
