/**
 * ogcapi-services
 * Server implementation of several OGC API Standards.
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Collection } from '../models/Collection';
import { Link } from '../models/Link';
import { HttpFile } from '../http/http';

export class Collections {
    'collections': Array<Collection>;
    'crs'?: Array<string>;
    'links'?: Array<Link>;
    'numberMatched'?: number | null;
    'numberReturned'?: number | null;
    'timeStamp'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "collections",
            "baseName": "collections",
            "type": "Array<Collection>",
            "format": ""
        },
        {
            "name": "crs",
            "baseName": "crs",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>",
            "format": ""
        },
        {
            "name": "numberMatched",
            "baseName": "numberMatched",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "numberReturned",
            "baseName": "numberReturned",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "timeStamp",
            "baseName": "timeStamp",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Collections.attributeTypeMap;
    }

    public constructor() {
    }
}
