/**
 * ogcapi-services
 * Server implementation of several OGC API Standards.
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Extent } from '../models/Extent';
import { Link } from '../models/Link';
import { HttpFile } from '../http/http';

/**
* A body of resources that belong or are used together. An aggregate, set, or group of related resources.
*/
export class Collection {
    /**
    * Attribution for the collection.
    */
    'attribution'?: string | null;
    /**
    * The list of coordinate reference systems supported by the API; the first item is the default coordinate reference system.
    */
    'crs'?: Array<string>;
    'description'?: string | null;
    'extent'?: Extent | null;
    'id': string;
    /**
    * An indicator about the type of the items in the collection.
    */
    'itemType'?: string;
    'keywords'?: Array<string>;
    'links'?: Array<Link>;
    'storageCrs'?: string;
    'storageCrsCoordinateEpoch'?: number | null;
    'title'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attribution",
            "baseName": "attribution",
            "type": "string",
            "format": ""
        },
        {
            "name": "crs",
            "baseName": "crs",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "extent",
            "baseName": "extent",
            "type": "Extent",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemType",
            "baseName": "itemType",
            "type": "string",
            "format": ""
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>",
            "format": ""
        },
        {
            "name": "storageCrs",
            "baseName": "storageCrs",
            "type": "string",
            "format": ""
        },
        {
            "name": "storageCrsCoordinateEpoch",
            "baseName": "storageCrsCoordinateEpoch",
            "type": "number",
            "format": "float"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Collection.attributeTypeMap;
    }

    public constructor() {
    }
}
