/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Constraints10Enum } from '../models/Constraints10Enum';
import { HttpFile } from '../http/http';

/**
* The following constraints are supported for `geopoint` fields.
*/
export class Constraints10 {
    /**
    * Indicates whether a property must have a value for each instance.
    */
    'required'?: boolean;
    /**
    * When `true`, each value for the property `MUST` be unique.
    */
    'unique'?: boolean;
    '_enum'?: Constraints10Enum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "unique",
            "baseName": "unique",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "_enum",
            "baseName": "enum",
            "type": "Constraints10Enum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Constraints10.attributeTypeMap;
    }

    public constructor() {
    }
}
