/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContactRole } from "../models/ContactRole";

/**
 * A request for pilot access, submitted via the contact form on the landing page.
 */
export class ContactRequest {
  "name": string;
  "email": string;
  "organization": string;
  "role": ContactRole;
  /**
   * Optional message, may be empty.
   */
  "message": string;
  /**
   * Must be `true`: the user agrees to the processing of their data.
   */
  "privacyConsent": boolean;
  /**
   * Must be left empty. Used to detect spam bots.
   */
  "website"?: string | null;

  static readonly discriminator: string | undefined = undefined;

  static readonly mapping: { [index: string]: string } | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "name",
      baseName: "name",
      type: "string",
      format: "",
    },
    {
      name: "email",
      baseName: "email",
      type: "string",
      format: "email",
    },
    {
      name: "organization",
      baseName: "organization",
      type: "string",
      format: "",
    },
    {
      name: "role",
      baseName: "role",
      type: "ContactRole",
      format: "",
    },
    {
      name: "message",
      baseName: "message",
      type: "string",
      format: "",
    },
    {
      name: "privacyConsent",
      baseName: "privacyConsent",
      type: "boolean",
      format: "",
    },
    {
      name: "website",
      baseName: "website",
      type: "string",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return ContactRequest.attributeTypeMap;
  }

  public constructor() {}
}
