/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AdditionalParameters } from '../models/AdditionalParameters';
import { Metadata } from '../models/Metadata';
import { HttpFile } from '../http/http';

/**
* Basic description type
*/
export class DescriptionType {
    'additionalParameters'?: AdditionalParameters;
    'description'?: string;
    'keywords'?: Array<string>;
    'metadata'?: Array<Metadata>;
    'title'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "additionalParameters",
            "baseName": "additionalParameters",
            "type": "AdditionalParameters",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "Array<Metadata>",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DescriptionType.attributeTypeMap;
    }

    public constructor() {
    }
}
