/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Documentation source for audit and provenance, e.g. a Geo Engine workflow or a scientific paper. This is included in the outputs of the process for traceability and auditing purposes.
*/
export class DocumentationSource {
    /**
    * A human-readable identifier of the documentation source (e.g. \"Geo Engine workflow XYZ\")
    */
    'data': string;
    /**
    * A description, citation or URL pointing to the source of the documentation (e.g. a link to a Geo Engine workflow, or a scientific paper)
    */
    'documentationSource': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "documentationSource",
            "baseName": "documentation_source",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentationSource.attributeTypeMap;
    }

    public constructor() {
    }
}
