/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Exception based on [`RFC 7807`](https://datatracker.ietf.org/doc/html/rfc7807)
*/
export class Exception {
    /**
    * A URI reference that identifies the problem type.
    */
    'type': string;
    /**
    * A short, human-readable summary of the problem type.
    */
    'title'?: string;
    /**
    * The HTTP status code generated by the origin server for this occurrence of the problem.
    */
    'status'?: number;
    /**
    * A human-readable explanation specific to this occurrence of the problem.
    */
    'detail'?: string;
    /**
    * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
    */
    'instance'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "string",
            "format": ""
        },
        {
            "name": "instance",
            "baseName": "instance",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Exception.attributeTypeMap;
    }

    public constructor() {
    }
}
