/**
 * ogcapi-services
 * Server implementation of several OGC API Standards.
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SpatialExtent } from '../models/SpatialExtent';
import { TemporalExtent } from '../models/TemporalExtent';
import { HttpFile } from '../http/http';

/**
* The extent of the features in the collection. In the Core only spatial and temporal extents are specified. Extensions may add additional members to represent other extents, for example, thermal or pressure ranges.
*/
export class Extent {
    'spatial': SpatialExtent;
    'temporal': TemporalExtent;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "spatial",
            "baseName": "spatial",
            "type": "SpatialExtent",
            "format": ""
        },
        {
            "name": "temporal",
            "baseName": "temporal",
            "type": "TemporalExtent",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Extent.attributeTypeMap;
    }

    public constructor() {
    }
}
