/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LandUseSiteSpecification } from "../models/LandUseSiteSpecification";

/**
 * Expected properties of a site feature in the input `GeoJSON`.
 */
export class FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInnerProperties {
  /**
   * Name of the site
   */
  "name"?: string;
  /**
   * Land-use type of the site
   */
  "type"?: LandUseSiteSpecification;

  static readonly discriminator: string | undefined = undefined;

  static readonly mapping: { [index: string]: string } | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "name",
      baseName: "name",
      type: "string",
      format: "",
    },
    {
      name: "type",
      baseName: "type",
      type: "LandUseSiteSpecification",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInnerProperties.attributeTypeMap;
  }

  public constructor() {}
}
