/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInner } from "../models/FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInner";

export class FeatureCollectionGeoJsonInputLandUseSitePropertiesValue {
  "type": FeatureCollectionGeoJsonInputLandUseSitePropertiesValueTypeEnum;
  "features": Array<FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInner>;
  "bbox"?: Array<number>;

  static readonly discriminator: string | undefined = undefined;

  static readonly mapping: { [index: string]: string } | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "type",
      baseName: "type",
      type: "FeatureCollectionGeoJsonInputLandUseSitePropertiesValueTypeEnum",
      format: "",
    },
    {
      name: "features",
      baseName: "features",
      type: "Array<FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInner>",
      format: "",
    },
    {
      name: "bbox",
      baseName: "bbox",
      type: "Array<number>",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return FeatureCollectionGeoJsonInputLandUseSitePropertiesValue.attributeTypeMap;
  }

  public constructor() {}
}

export enum FeatureCollectionGeoJsonInputLandUseSitePropertiesValueTypeEnum {
  FeatureCollection = "FeatureCollection",
}
