/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValueAllOfFeaturesInnerGeometry } from "../models/FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValueAllOfFeaturesInnerGeometry";
import { FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValueAllOfFeaturesInnerProperties } from "../models/FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValueAllOfFeaturesInnerProperties";

export class FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValueAllOfFeaturesInner {
  "geometry"?: FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValueAllOfFeaturesInnerGeometry;
  "properties"?: FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValueAllOfFeaturesInnerProperties;

  static readonly discriminator: string | undefined = undefined;

  static readonly mapping: { [index: string]: string } | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "geometry",
      baseName: "geometry",
      type: "FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValueAllOfFeaturesInnerGeometry",
      format: "",
    },
    {
      name: "properties",
      baseName: "properties",
      type: "FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValueAllOfFeaturesInnerProperties",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValueAllOfFeaturesInner.attributeTypeMap;
  }

  public constructor() {}
}
