/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GeoJSONFeatureCollection } from '../models/GeoJSONFeatureCollection';
import { GeoJsonInputMediaType } from '../models/GeoJsonInputMediaType';
import { HttpFile } from '../http/http';

/**
* A `GeoJSON` `FeatureCollection` input
*/
export class FeatureCollectionGeoJsonInput {
    'value': GeoJSONFeatureCollection;
    'mediaType': GeoJsonInputMediaType;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "GeoJSONFeatureCollection",
            "format": ""
        },
        {
            "name": "mediaType",
            "baseName": "mediaType",
            "type": "GeoJsonInputMediaType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FeatureCollectionGeoJsonInput.attributeTypeMap;
    }

    public constructor() {
    }
}


