/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValue } from "../models/FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValue";
import { GeoJsonInputMediaType } from "../models/GeoJsonInputMediaType";

/**
 * A `GeoJSON` `FeatureCollection` input
 */
export class FeatureCollectionGeoJsonInputBiodiversitySiteProperties {
  "value": FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValue;
  "mediaType": GeoJsonInputMediaType;

  static readonly discriminator: string | undefined = undefined;

  static readonly mapping: { [index: string]: string } | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "value",
      baseName: "value",
      type: "FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValue",
      format: "",
    },
    {
      name: "mediaType",
      baseName: "mediaType",
      type: "GeoJsonInputMediaType",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return FeatureCollectionGeoJsonInputBiodiversitySiteProperties.attributeTypeMap;
  }

  public constructor() {}
}
