/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInnerGeometry } from "../models/FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInnerGeometry";
import { FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInnerProperties } from "../models/FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInnerProperties";

export class FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInner {
  "geometry"?: FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInnerGeometry;
  "properties"?: FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInnerProperties;

  static readonly discriminator: string | undefined = undefined;

  static readonly mapping: { [index: string]: string } | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "geometry",
      baseName: "geometry",
      type: "FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInnerGeometry",
      format: "",
    },
    {
      name: "properties",
      baseName: "properties",
      type: "FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInnerProperties",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return FeatureCollectionGeoJsonInputLandUseSitePropertiesValueAllOfFeaturesInner.attributeTypeMap;
  }

  public constructor() {}
}
