/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BiodiversitySiteSpecification } from '../models/BiodiversitySiteSpecification';
import { HttpFile } from '../http/http';

/**
* Expected properties of a site feature in the input `GeoJSON`.
*/
export class FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValueAllOfFeaturesInnerProperties {
    /**
    * Name of the site
    */
    'name'?: string;
    /**
    * Type of the site, which determines its impact radius
    */
    'type'?: BiodiversitySiteSpecification;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BiodiversitySiteSpecification",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FeatureCollectionGeoJsonInputBiodiversitySitePropertiesValueAllOfFeaturesInnerProperties.attributeTypeMap;
    }

    public constructor() {
    }
}


