/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GeoJSONFeature } from '../models/GeoJSONFeature';
import { HttpFile } from '../http/http';

export class GeoJSONFeatureCollection {
    'type': GeoJSONFeatureCollectionTypeEnum;
    'features': Array<GeoJSONFeature>;
    'bbox'?: Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GeoJSONFeatureCollectionTypeEnum",
            "format": ""
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "Array<GeoJSONFeature>",
            "format": ""
        },
        {
            "name": "bbox",
            "baseName": "bbox",
            "type": "Array<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GeoJSONFeatureCollection.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum GeoJSONFeatureCollectionTypeEnum {
    FeatureCollection = 'FeatureCollection'
}

