/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GeoJSONGeometryCollectionGeometriesInner } from '../models/GeoJSONGeometryCollectionGeometriesInner';
import { HttpFile } from '../http/http';

export class GeoJSONGeometryCollection {
    'type': GeoJSONGeometryCollectionTypeEnum;
    'geometries': Array<GeoJSONGeometryCollectionGeometriesInner>;
    'bbox'?: Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GeoJSONGeometryCollectionTypeEnum",
            "format": ""
        },
        {
            "name": "geometries",
            "baseName": "geometries",
            "type": "Array<GeoJSONGeometryCollectionGeometriesInner>",
            "format": ""
        },
        {
            "name": "bbox",
            "baseName": "bbox",
            "type": "Array<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GeoJSONGeometryCollection.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum GeoJSONGeometryCollectionTypeEnum {
    GeometryCollection = 'GeometryCollection'
}

