/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GeoJSONGeometryCollection } from '../models/GeoJSONGeometryCollection';
import { GeoJSONLineString } from '../models/GeoJSONLineString';
import { GeoJSONMultiLineString } from '../models/GeoJSONMultiLineString';
import { GeoJSONMultiPoint } from '../models/GeoJSONMultiPoint';
import { GeoJSONMultiPolygon } from '../models/GeoJSONMultiPolygon';
import { GeoJSONPoint } from '../models/GeoJSONPoint';
import { GeoJSONPolygon } from '../models/GeoJSONPolygon';
import { HttpFile } from '../http/http';

/**
 * @type GeoJSONFeatureGeometry
 * Type
 * @export
 */
export type GeoJSONFeatureGeometry = GeoJSONGeometryCollection | GeoJSONLineString | GeoJSONMultiLineString | GeoJSONMultiPoint | GeoJSONMultiPolygon | GeoJSONPoint | GeoJSONPolygon;

/**
* @type GeoJSONFeatureGeometryClass
* @export
*/
export class GeoJSONFeatureGeometryClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}






