/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Constraints10 } from '../models/Constraints10';
import { StringFieldMissingValues } from '../models/StringFieldMissingValues';
import { HttpFile } from '../http/http';

/**
* The field contains data describing a geographic point.
*/
export class GeoPointField {
    /**
    * A name for this field.
    */
    'name': string;
    /**
    * A human-readable title.
    */
    'title'?: string;
    /**
    * A text description. Markdown is encouraged.
    */
    'description'?: string;
    /**
    * An example value for the field.
    */
    'example'?: string;
    'missingValues'?: StringFieldMissingValues;
    /**
    * The type keyword, which `MUST` be a value of `geopoint`.
    */
    'type': GeoPointFieldTypeEnum;
    /**
    * The format keyword options for `geopoint` are `default`,`array`, and `object`.
    */
    'format'?: GeoPointFieldFormatEnum;
    'constraints'?: Constraints10;
    /**
    * The RDF type for this field.
    */
    'rdfType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "example",
            "baseName": "example",
            "type": "string",
            "format": ""
        },
        {
            "name": "missingValues",
            "baseName": "missingValues",
            "type": "StringFieldMissingValues",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "GeoPointFieldTypeEnum",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "GeoPointFieldFormatEnum",
            "format": ""
        },
        {
            "name": "constraints",
            "baseName": "constraints",
            "type": "Constraints10",
            "format": ""
        },
        {
            "name": "rdfType",
            "baseName": "rdfType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GeoPointField.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum GeoPointFieldTypeEnum {
    Geopoint = 'geopoint'
}
export enum GeoPointFieldFormatEnum {
    Default = 'default',
    Array = 'array',
    Object = 'object'
}

