/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreditsForJob } from '../models/CreditsForJob';
import { HttpFile } from '../http/http';

export class GetCreditsResponse {
    'year': number;
    'month': number;
    'creditsUsed': number;
    'details': Array<CreditsForJob>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "year",
            "baseName": "year",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "month",
            "baseName": "month",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "creditsUsed",
            "baseName": "creditsUsed",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "Array<CreditsForJob>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetCreditsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
