/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Link } from '../models/Link';
import { QualifiedInputValue } from '../models/QualifiedInputValue';
import { HttpFile } from '../http/http';

/**
 * @type InlineOrRefData
 * Type
 * @export
 */
export type InlineOrRefData = Link | QualifiedInputValue | any;

/**
* @type InlineOrRefDataClass
* @export
*/
export class InlineOrRefDataClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


