/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AdditionalParameters } from '../models/AdditionalParameters';
import { DescriptionType } from '../models/DescriptionType';
import { MaxOccurs } from '../models/MaxOccurs';
import { Metadata } from '../models/Metadata';
import { HttpFile } from '../http/http';

/**
* Process input description
*/
export class InputDescription extends DescriptionType {
    'minOccurs'?: number | null;
    'maxOccurs'?: MaxOccurs | null;
    'schema': any | null;

    static override readonly discriminator: string | undefined = undefined;

    static override readonly mapping: {[index: string]: string} | undefined = undefined;

    static override readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "minOccurs",
            "baseName": "minOccurs",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxOccurs",
            "baseName": "maxOccurs",
            "type": "MaxOccurs",
            "format": ""
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "any",
            "format": ""
        }    ];

    static override getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(InputDescription.attributeTypeMap);
    }

    public constructor() {
        super();
    }
}
