/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineOrRefData } from '../models/InlineOrRefData';
import { HttpFile } from '../http/http';

/**
* Process execution input
*/
/**
 * @type Input
 * Type
 * @export
 */
export type Input = Array<InlineOrRefData> | InlineOrRefData;

/**
* @type InputClass
    * Process execution input
* @export
*/
export class InputClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

