/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Constraints2 } from '../models/Constraints2';
import { StringFieldCategories } from '../models/StringFieldCategories';
import { StringFieldMissingValues } from '../models/StringFieldMissingValues';
import { HttpFile } from '../http/http';

/**
* The field contains integers - that is whole numbers.
*/
export class IntegerField {
    /**
    * A name for this field.
    */
    'name': string;
    /**
    * A human-readable title.
    */
    'title'?: string;
    /**
    * A text description. Markdown is encouraged.
    */
    'description'?: string;
    /**
    * An example value for the field.
    */
    'example'?: string;
    'missingValues'?: StringFieldMissingValues;
    'categories'?: StringFieldCategories;
    'categoriesOrdered'?: boolean;
    /**
    * The type keyword, which `MUST` be a value of `integer`.
    */
    'type': IntegerFieldTypeEnum;
    /**
    * There are no format keyword options for `integer`: only `default` is allowed.
    */
    'format'?: IntegerFieldFormatEnum;
    /**
    * a boolean field with a default of `true`. If `true` the physical contents of this field must follow the formatting constraints already set out. If `false` the contents of this field may contain leading and/or trailing non-numeric characters (which implementors MUST therefore strip). The purpose of `bareNumber` is to allow publishers to publish numeric data that contains trailing characters such as percentages e.g. `95%` or leading characters such as currencies e.g. `€95` or `EUR 95`. Note that it is entirely up to implementors what, if anything, they do with stripped text.
    */
    'bareNumber'?: boolean;
    /**
    * A string whose value is used to group digits within the number. This property does not have a default value. A common value is `,` e.g. \'100,000\'.
    */
    'groupChar'?: string;
    'constraints'?: Constraints2;
    /**
    * The RDF type for this field.
    */
    'rdfType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "example",
            "baseName": "example",
            "type": "string",
            "format": ""
        },
        {
            "name": "missingValues",
            "baseName": "missingValues",
            "type": "StringFieldMissingValues",
            "format": ""
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "StringFieldCategories",
            "format": ""
        },
        {
            "name": "categoriesOrdered",
            "baseName": "categoriesOrdered",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "IntegerFieldTypeEnum",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "IntegerFieldFormatEnum",
            "format": ""
        },
        {
            "name": "bareNumber",
            "baseName": "bareNumber",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "groupChar",
            "baseName": "groupChar",
            "type": "string",
            "format": ""
        },
        {
            "name": "constraints",
            "baseName": "constraints",
            "type": "Constraints2",
            "format": ""
        },
        {
            "name": "rdfType",
            "baseName": "rdfType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IntegerField.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum IntegerFieldTypeEnum {
    Integer = 'integer'
}
export enum IntegerFieldFormatEnum {
    Default = 'default'
}

