/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JsonInputMediaType } from '../models/JsonInputMediaType';
import { JsonInputPreviousLandUseSummaryValue } from '../models/JsonInputPreviousLandUseSummaryValue';
import { HttpFile } from '../http/http';

/**
* Helper struct to define complex input specifications for processes.
*/
export class JsonInputPreviousLandUseSummary {
    'value': JsonInputPreviousLandUseSummaryValue;
    'mediaType': JsonInputMediaType;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "JsonInputPreviousLandUseSummaryValue",
            "format": ""
        },
        {
            "name": "mediaType",
            "baseName": "mediaType",
            "type": "JsonInputMediaType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JsonInputPreviousLandUseSummary.attributeTypeMap;
    }

    public constructor() {
    }
}


