/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UnitForArea } from '../models/UnitForArea';
import { HttpFile } from '../http/http';

/**
* If the previous year data is available, it will be used to calculate the percentage change for each land use category.
*/
export class JsonInputPreviousLandUseSummaryValue {
    /**
    * Total sealed area
    */
    'totalSealedArea': number;
    /**
    * Total nature-oriented area on-site
    */
    'totalNatureOnSiteArea': number;
    /**
    * Total nature-oriented area off-site
    */
    'totalNatureOffSiteArea': number;
    /**
    * Total use of land
    */
    'totalUseOfLand': number;
    /**
    * Unit for area values (e.g., \"ha\" for hectares, \"m²\" for square meters)
    */
    'unitForArea': UnitForArea;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "totalSealedArea",
            "baseName": "totalSealedArea",
            "type": "number",
            "format": "double"
        },
        {
            "name": "totalNatureOnSiteArea",
            "baseName": "totalNatureOnSiteArea",
            "type": "number",
            "format": "double"
        },
        {
            "name": "totalNatureOffSiteArea",
            "baseName": "totalNatureOffSiteArea",
            "type": "number",
            "format": "double"
        },
        {
            "name": "totalUseOfLand",
            "baseName": "totalUseOfLand",
            "type": "number",
            "format": "double"
        },
        {
            "name": "unitForArea",
            "baseName": "unitForArea",
            "type": "UnitForArea",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JsonInputPreviousLandUseSummaryValue.attributeTypeMap;
    }

    public constructor() {
    }
}


