/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Hyperlink to enable Hypermedia Access
*/
export class Link {
    /**
    * Supplies the URI to a remote resource (or resource fragment).
    */
    'href': string;
    /**
    * The type or semantics of the relation.
    */
    'rel': string;
    /**
    * A hint indicating what the media type of the result of dereferencing the link should be.
    */
    'type'?: string;
    /**
    * This flag set to true if the link is a URL template.
    */
    'templated'?: boolean;
    /**
    * A base path to retrieve semantic information about the variables used in URL template.
    */
    'varBase'?: string;
    /**
    * A hint indicating what the language of the result of dereferencing the link should be.
    */
    'hreflang'?: string;
    /**
    * Used to label the destination of a link such that it can be used as a human-readable identifier.
    */
    'title'?: string;
    'length'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "rel",
            "baseName": "rel",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "templated",
            "baseName": "templated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "varBase",
            "baseName": "varBase",
            "type": "string",
            "format": ""
        },
        {
            "name": "hreflang",
            "baseName": "hreflang",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return Link.attributeTypeMap;
    }

    public constructor() {
    }
}
