/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Metadata {
    'title'?: string;
    'role'?: string;
    'href'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Metadata.attributeTypeMap;
    }

    public constructor() {
    }
}
