/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PointGeoJsonInput } from '../models/PointGeoJsonInput';
import { HttpFile } from '../http/http';

export class NDVIProcessInputs {
    'coordinate': PointGeoJsonInput;
    'year': number;
    'month': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "coordinate",
            "baseName": "coordinate",
            "type": "PointGeoJsonInput",
            "format": ""
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "month",
            "baseName": "month",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return NDVIProcessInputs.attributeTypeMap;
    }

    public constructor() {
    }
}
