/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Constraints1 } from '../models/Constraints1';
import { StringFieldMissingValues } from '../models/StringFieldMissingValues';
import { HttpFile } from '../http/http';

/**
* The field contains numbers of any kind including decimals.
*/
export class NumberField {
    /**
    * A name for this field.
    */
    'name': string;
    /**
    * A human-readable title.
    */
    'title'?: string;
    /**
    * A text description. Markdown is encouraged.
    */
    'description'?: string;
    /**
    * An example value for the field.
    */
    'example'?: string;
    'missingValues'?: StringFieldMissingValues;
    /**
    * The type keyword, which `MUST` be a value of `number`.
    */
    'type': NumberFieldTypeEnum;
    /**
    * There are no format keyword options for `number`: only `default` is allowed.
    */
    'format'?: NumberFieldFormatEnum;
    /**
    * a boolean field with a default of `true`. If `true` the physical contents of this field must follow the formatting constraints already set out. If `false` the contents of this field may contain leading and/or trailing non-numeric characters (which implementors MUST therefore strip). The purpose of `bareNumber` is to allow publishers to publish numeric data that contains trailing characters such as percentages e.g. `95%` or leading characters such as currencies e.g. `€95` or `EUR 95`. Note that it is entirely up to implementors what, if anything, they do with stripped text.
    */
    'bareNumber'?: boolean;
    /**
    * A string whose value is used to group digits within the number. This property does not have a default value. A common value is `,` e.g. \'100,000\'.
    */
    'groupChar'?: string;
    /**
    * A string whose value is used to represent a decimal point within the number. The default value is `.`.
    */
    'decimalChar'?: string;
    'constraints'?: Constraints1;
    /**
    * The RDF type for this field.
    */
    'rdfType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "example",
            "baseName": "example",
            "type": "string",
            "format": ""
        },
        {
            "name": "missingValues",
            "baseName": "missingValues",
            "type": "StringFieldMissingValues",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "NumberFieldTypeEnum",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "NumberFieldFormatEnum",
            "format": ""
        },
        {
            "name": "bareNumber",
            "baseName": "bareNumber",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "groupChar",
            "baseName": "groupChar",
            "type": "string",
            "format": ""
        },
        {
            "name": "decimalChar",
            "baseName": "decimalChar",
            "type": "string",
            "format": ""
        },
        {
            "name": "constraints",
            "baseName": "constraints",
            "type": "Constraints1",
            "format": ""
        },
        {
            "name": "rdfType",
            "baseName": "rdfType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NumberField.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum NumberFieldTypeEnum {
    Number = 'number'
}
export enum NumberFieldFormatEnum {
    Default = 'default'
}

