/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Format } from '../models/Format';
import { TransmissionMode } from '../models/TransmissionMode';
import { HttpFile } from '../http/http';

/**
* Process execution output
*/
export class Output {
    'format'?: Format;
    'transmissionMode'?: TransmissionMode;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "format",
            "baseName": "format",
            "type": "Format",
            "format": ""
        },
        {
            "name": "transmissionMode",
            "baseName": "transmissionMode",
            "type": "TransmissionMode",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Output.attributeTypeMap;
    }

    public constructor() {
    }
}


