/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DescriptionType } from "../models/DescriptionType";

/**
 * Process output description
 */
export class OutputDescription extends DescriptionType {
  "schema": any | null;

  static override readonly discriminator: string | undefined = undefined;

  static override readonly mapping: { [index: string]: string } | undefined =
    undefined;

  static override readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "schema",
      baseName: "schema",
      type: "any",
      format: "",
    },
  ];

  static override getAttributeTypeMap() {
    return super
      .getAttributeTypeMap()
      .concat(OutputDescription.attributeTypeMap);
  }

  public constructor() {
    super();
  }
}
