/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A reference to the data for this resource, as either a path as a string, or an array of paths as strings. of valid URIs.
*/
/**
 * @type Path
 * Type
 * @export
 */
export type Path = Array<string> | string;

/**
* @type PathClass
    * A reference to the data for this resource, as either a path as a string, or an array of paths as strings. of valid URIs.
* @export
*/
export class PathClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

