/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PointGeoJson } from '../models/PointGeoJson';
import { PointGeoJsonInputMediaType } from '../models/PointGeoJsonInputMediaType';
import { HttpFile } from '../http/http';

export class PointGeoJsonInput {
    'mediaType': PointGeoJsonInputMediaType;
    'value': PointGeoJson;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mediaType",
            "baseName": "mediaType",
            "type": "PointGeoJsonInputMediaType",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "PointGeoJson",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PointGeoJsonInput.attributeTypeMap;
    }

    public constructor() {
    }
}


