/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PointGeoJsonType } from '../models/PointGeoJsonType';
import { HttpFile } from '../http/http';

export class PointGeoJson {
    'coordinates': Array<number>;
    'type': PointGeoJsonType;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "coordinates",
            "baseName": "coordinates",
            "type": "Array<number>",
            "format": "double"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PointGeoJsonType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PointGeoJson.attributeTypeMap;
    }

    public constructor() {
    }
}


