/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InputDescription } from '../models/InputDescription';
import { JobControlOptions } from '../models/JobControlOptions';
import { Link } from '../models/Link';
import { OutputDescription } from '../models/OutputDescription';
import { ProcessSummary } from '../models/ProcessSummary';
import { TransmissionMode } from '../models/TransmissionMode';
import { HttpFile } from '../http/http';

/**
* Full process description
*/
export class Process extends ProcessSummary {
    'inputs'?: { [key: string]: InputDescription; };
    'outputs'?: { [key: string]: OutputDescription; };

    static override readonly discriminator: string | undefined = undefined;

    static override readonly mapping: {[index: string]: string} | undefined = undefined;

    static override readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "{ [key: string]: InputDescription; }",
            "format": ""
        },
        {
            "name": "outputs",
            "baseName": "outputs",
            "type": "{ [key: string]: OutputDescription; }",
            "format": ""
        }    ];

    static override getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(Process.attributeTypeMap);
    }

    public constructor() {
        super();
    }
}
