/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JobControlOptions } from '../models/JobControlOptions';
import { Link } from '../models/Link';
import { TransmissionMode } from '../models/TransmissionMode';
import { HttpFile } from '../http/http';

/**
* Process summary
*/
export class ProcessSummary {
    'id': string;
    'version': string;
    'jobControlOptions'?: Array<JobControlOptions>;
    'outputTransmission'?: Array<TransmissionMode>;
    'links'?: Array<Link>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobControlOptions",
            "baseName": "jobControlOptions",
            "type": "Array<JobControlOptions>",
            "format": ""
        },
        {
            "name": "outputTransmission",
            "baseName": "outputTransmission",
            "type": "Array<TransmissionMode>",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProcessSummary.attributeTypeMap;
    }

    public constructor() {
    }
}
