/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Link } from '../models/Link';
import { ProcessSummary } from '../models/ProcessSummary';
import { HttpFile } from '../http/http';

/**
* Information about the available processes
*/
export class ProcessList {
    'links': Array<Link>;
    'processes': Array<ProcessSummary>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>",
            "format": ""
        },
        {
            "name": "processes",
            "baseName": "processes",
            "type": "Array<ProcessSummary>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProcessList.attributeTypeMap;
    }

    public constructor() {
    }
}
