/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Format } from '../models/Format';
import { InputValue } from '../models/InputValue';
import { Schema } from '../models/Schema';
import { HttpFile } from '../http/http';

export class QualifiedInputValue extends Format {
    'value': InputValue;

    static override readonly discriminator: string | undefined = undefined;

    static override readonly mapping: {[index: string]: string} | undefined = undefined;

    static override readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "InputValue",
            "format": ""
        }    ];

    static override getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(QualifiedInputValue.attributeTypeMap);
    }

    public constructor() {
        super();
    }
}
