/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SiteRow {
    'location': string;
    'areaHa': number;
    /**
    * Area in hectares
    */
    'biodiversitySensitiveAreaHa': number;
    'specification': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "areaHa",
            "baseName": "area_ha",
            "type": "number",
            "format": "double"
        },
        {
            "name": "biodiversitySensitiveAreaHa",
            "baseName": "biodiversity_sensitive_area_ha",
            "type": "number",
            "format": "double"
        },
        {
            "name": "specification",
            "baseName": "specification",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SiteRow.attributeTypeMap;
    }

    public constructor() {
    }
}
