/**
 * ogcapi-services
 * Server implementation of several OGC API Standards.
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The spatial extent of the features in the collection.
*/
export class SpatialExtent {
    /**
    * One or more bounding boxes that describe the spatial extent of the dataset. In the Core only a single bounding box is supported. Extensions may support additional areas. If multiple areas are provided, the union of the bounding boxes describes the spatial extent.
    */
    'bbox'?: Array<Array<number>>;
    /**
    * Coordinate reference system of the coordinates in the spatial extent (property `bbox`). The default reference system is WGS 84 longitude/latitude. In the Core this is the only supported coordinate reference system. Extensions may support additional coordinate reference systems and add additional enum values.
    */
    'crs'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bbox",
            "baseName": "bbox",
            "type": "Array<Array<number>>",
            "format": "double"
        },
        {
            "name": "crs",
            "baseName": "crs",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SpatialExtent.attributeTypeMap;
    }

    public constructor() {
    }
}
