/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JobType } from '../models/JobType';
import { Link } from '../models/Link';
import { StatusCode } from '../models/StatusCode';
import { HttpFile } from '../http/http';

export class StatusInfo {
    'processID'?: string;
    'type'?: JobType;
    'jobID': string;
    'status': StatusCode;
    'message'?: string;
    'created'?: Date;
    'finished'?: Date;
    'updated'?: Date;
    'progress'?: number;
    'links'?: Array<Link>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "processID",
            "baseName": "processID",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "JobType",
            "format": ""
        },
        {
            "name": "jobID",
            "baseName": "jobID",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "StatusCode",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "finished",
            "baseName": "finished",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "progress",
            "baseName": "progress",
            "type": "number",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StatusInfo.attributeTypeMap;
    }

    public constructor() {
    }
}


