/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Constraints } from '../models/Constraints';
import { StringFieldCategories } from '../models/StringFieldCategories';
import { StringFieldMissingValues } from '../models/StringFieldMissingValues';
import { HttpFile } from '../http/http';

/**
* The field contains strings, that is, sequences of characters.
*/
export class StringField {
    /**
    * A name for this field.
    */
    'name': string;
    /**
    * A human-readable title.
    */
    'title'?: string;
    /**
    * A text description. Markdown is encouraged.
    */
    'description'?: string;
    /**
    * An example value for the field.
    */
    'example'?: string;
    'missingValues'?: StringFieldMissingValues;
    'categories'?: StringFieldCategories;
    'categoriesOrdered'?: boolean;
    /**
    * The type keyword, which `MUST` be a value of `string`.
    */
    'type'?: StringFieldTypeEnum;
    /**
    * The format keyword options for `string` are `default`, `email`, `uri`, `binary`, and `uuid`.
    */
    'format'?: StringFieldFormatEnum;
    'constraints'?: Constraints;
    /**
    * The RDF type for this field.
    */
    'rdfType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "example",
            "baseName": "example",
            "type": "string",
            "format": ""
        },
        {
            "name": "missingValues",
            "baseName": "missingValues",
            "type": "StringFieldMissingValues",
            "format": ""
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "StringFieldCategories",
            "format": ""
        },
        {
            "name": "categoriesOrdered",
            "baseName": "categoriesOrdered",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "StringFieldTypeEnum",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "StringFieldFormatEnum",
            "format": ""
        },
        {
            "name": "constraints",
            "baseName": "constraints",
            "type": "Constraints",
            "format": ""
        },
        {
            "name": "rdfType",
            "baseName": "rdfType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StringField.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum StringFieldTypeEnum {
    String = 'string'
}
export enum StringFieldFormatEnum {
    Default = 'default',
    Email = 'email',
    Uri = 'uri',
    Binary = 'binary',
    Uuid = 'uuid'
}

