/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The Table dialect descriptor.
*/
export class TableDialect {
    /**
    * The profile of this descriptor.
    */
    'schema'?: string;
    /**
    * Specifies if the file includes a header row, always as the first row in the file.
    */
    'header'?: boolean;
    'headerRows'?: Array<number>;
    'headerJoin'?: string;
    'commentRows'?: Array<number>;
    /**
    * Specifies that any row beginning with this one-character string, without preceeding whitespace, causes the entire line to be ignored.
    */
    'commentChar'?: string;
    /**
    * A character sequence to use as the field separator.
    */
    'delimiter'?: string;
    /**
    * Specifies the character sequence that must be used to terminate rows.
    */
    'lineTerminator'?: string;
    /**
    * Specifies a one-character string to use as the quoting character.
    */
    'quoteChar'?: string;
    /**
    * Specifies the handling of quotes inside fields.
    */
    'doubleQuote'?: boolean;
    /**
    * Specifies a one-character string to use as the escape character.
    */
    'escapeChar'?: string;
    /**
    * Specifies the null sequence, for example, `\\N`.
    */
    'nullSequence'?: string;
    /**
    * Specifies the interpretation of whitespace immediately following a delimiter. If false, whitespace immediately after a delimiter should be treated as part of the subsequent field.
    */
    'skipInitialSpace'?: boolean;
    'property'?: string;
    'itemType'?: TableDialectItemTypeEnum;
    'itemKeys'?: Array<string>;
    'sheetNumber'?: number;
    'sheetName'?: string;
    'table'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "$schema",
            "type": "string",
            "format": ""
        },
        {
            "name": "header",
            "baseName": "header",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "headerRows",
            "baseName": "headerRows",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "headerJoin",
            "baseName": "headerJoin",
            "type": "string",
            "format": ""
        },
        {
            "name": "commentRows",
            "baseName": "commentRows",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "commentChar",
            "baseName": "commentChar",
            "type": "string",
            "format": ""
        },
        {
            "name": "delimiter",
            "baseName": "delimiter",
            "type": "string",
            "format": ""
        },
        {
            "name": "lineTerminator",
            "baseName": "lineTerminator",
            "type": "string",
            "format": ""
        },
        {
            "name": "quoteChar",
            "baseName": "quoteChar",
            "type": "string",
            "format": ""
        },
        {
            "name": "doubleQuote",
            "baseName": "doubleQuote",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "escapeChar",
            "baseName": "escapeChar",
            "type": "string",
            "format": ""
        },
        {
            "name": "nullSequence",
            "baseName": "nullSequence",
            "type": "string",
            "format": ""
        },
        {
            "name": "skipInitialSpace",
            "baseName": "skipInitialSpace",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemType",
            "baseName": "itemType",
            "type": "TableDialectItemTypeEnum",
            "format": ""
        },
        {
            "name": "itemKeys",
            "baseName": "itemKeys",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "sheetNumber",
            "baseName": "sheetNumber",
            "type": "number",
            "format": ""
        },
        {
            "name": "sheetName",
            "baseName": "sheetName",
            "type": "string",
            "format": ""
        },
        {
            "name": "table",
            "baseName": "table",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TableDialect.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum TableDialectItemTypeEnum {
    Array = 'array',
    Object = 'object'
}

