/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A primary key is a field name or an array of field names, whose values `MUST` uniquely identify each row in the table.
*/
/**
 * @type TableSchemaPrimaryKey
 * Type
 * @export
 */
export type TableSchemaPrimaryKey = Set<string> | string;

/**
* @type TableSchemaPrimaryKeyClass
    * A primary key is a field name or an array of field names, whose values `MUST` uniquely identify each row in the table.
* @export
*/
export class TableSchemaPrimaryKeyClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

