/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TableSchemaForeignKeyOneOf } from '../models/TableSchemaForeignKeyOneOf';
import { TableSchemaForeignKeyOneOf1 } from '../models/TableSchemaForeignKeyOneOf1';
import { HttpFile } from '../http/http';

/**
* Table Schema Foreign Key
*/
/**
 * @type TableSchemaForeignKey
 * Type
 * @export
 */
export type TableSchemaForeignKey = TableSchemaForeignKeyOneOf | TableSchemaForeignKeyOneOf1;

/**
* @type TableSchemaForeignKeyClass
    * Table Schema Foreign Key
* @export
*/
export class TableSchemaForeignKeyClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

