/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TableSchemaForeignKeyOneOf1Reference } from '../models/TableSchemaForeignKeyOneOf1Reference';
import { HttpFile } from '../http/http';

export class TableSchemaForeignKeyOneOf1 {
    /**
    * Fields that make up the primary key.
    */
    'fields'?: string;
    'reference'?: TableSchemaForeignKeyOneOf1Reference;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fields",
            "baseName": "fields",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "TableSchemaForeignKeyOneOf1Reference",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TableSchemaForeignKeyOneOf1.attributeTypeMap;
    }

    public constructor() {
    }
}
