/**
 * ogcapi-services
 * Server implementation of several OGC API Standards.
 *
 * OpenAPI spec version: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The temporal extent of the features in the collection.
*/
export class TemporalExtent {
    /**
    * One or more time intervals that describe the temporal extent of the dataset. The value `null` is supported and indicates an unbounded interval end. In the Core only a single time interval is supported. Extensions may support multiple intervals. If multiple intervals are provided, the union of the intervals describes the temporal extent.
    */
    'interval': Array<Array<Date | null>>;
    /**
    * Coordinate reference system of the coordinates in the temporal extent (property `interval`). The default reference system is the Gregorian calendar. In the Core this is the only supported temporal coordinate reference system. Extensions may support additional temporal coordinate reference systems and add additional enum values.
    */
    'trs'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "interval",
            "baseName": "interval",
            "type": "Array<Array<Date | null>>",
            "format": "date-time"
        },
        {
            "name": "trs",
            "baseName": "trs",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TemporalExtent.attributeTypeMap;
    }

    public constructor() {
    }
}
