/**
 * BioIS API
 * API for the BioIS service, providing access to geospatial processing and job management.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: info@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserInfo } from '../models/UserInfo';
import { HttpFile } from '../http/http';

export class UserSession {
    'created': string;
    'id': string;
    'roles': Array<string>;
    'user': UserInfo;
    'validUntil': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "created",
            "baseName": "created",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "UserInfo",
            "format": ""
        },
        {
            "name": "validUntil",
            "baseName": "validUntil",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserSession.attributeTypeMap;
    }

    public constructor() {
    }
}
