name: CI

on:
  pull_request:
  merge_group:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    lint-backend:
        name: Lint Backend

        runs-on: ubuntu-24.04
        container: quay.io/geoengine/devcontainer:latest

        permissions:
            contents: read

        defaults:
            run:
                working-directory: ./backend
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            - name: Init rustup toolchain
              run: rustup show
            - name: setup rust build cache
              uses: Swatinem/rust-cache@v2
              with:
                # An explicit cache key that is used instead of the automatic `job`-based
                # cache key and is thus stable across jobs.
                # Default: empty
                shared-key: ""
    
                # An additional cache key that is added alongside the automatic `job`-based
                # cache key and can be used to further differentiate jobs.
                # Default: empty
                key: ci_test_
            - name: Rustfmt
              run: ./lint.sh rustfmt
            - name: Clippy
              run: ./lint.sh clippy
            - name: SQLFluff
              run: ./lint.sh sqlfluff
            - name: Start PostgreSQL
              run: |
                service postgresql start
                psql postgres://geoengine:geoengine@localhost -c "CREATE DATABASE biois;"
            - name: Diesel Check
              run: ./lint.sh diesel_cli --with-install
              env:
                DATABASE_URL: postgres://geoengine:geoengine@localhost/biois

    test-backend:
        name: Test Backend

        runs-on: ubuntu-24.04
        container: quay.io/geoengine/devcontainer:latest

        permissions:
            contents: read

        outputs:
            coverage-artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}

        defaults:
            run:
                working-directory: ./backend
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            - name: Init rustup toolchain
              run: rustup show

            - name: Start PostgreSQL
              run: |
                service postgresql start
                psql postgres://geoengine:geoengine@localhost -c "CREATE DATABASE biois;"
            - name: setup rust build cache
              uses: Swatinem/rust-cache@v2
              with:
                # An explicit cache key that is used instead of the automatic `job`-based
                # cache key and is thus stable across jobs.
                # Default: empty
                shared-key: ""
    
                # An additional cache key that is added alongside the automatic `job`-based
                # cache key and can be used to further differentiate jobs.
                # Default: empty
                key: ci_test_
            - name: Test
              run: |
                cargo install --locked cargo-llvm-cov

                cargo llvm-cov \
                    --locked \
                    --all-features \
                    --lcov \
                    --output-path lcov.info
            - id: upload-artifact
              uses: actions/upload-artifact@v6
              with:
                name: lcov-report-backend-${{ github.run_id }}-${{ github.run_attempt }}
                path: lcov.info
                compression-level: 9
                retention-days: 1
                if-no-files-found: error
            
    upload-coverage:
        name: Upload Coverage Report

        runs-on: ubuntu-24.04

        permissions:
            contents: read

        needs:
            - test-backend

        steps:
            - name: Download Backend Coverage Report
              uses: actions/download-artifact@v7
              with:
                artifact-ids: ${{ needs.test-backend.outputs.coverage-artifact-id }}
                path: lcov-backend.info
            - name: Upload coverage to Coveralls
              uses: coverallsapp/github-action@v2
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                file: lcov-backend.info